language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install
  - npm i

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
  - ./node_modules/.bin/gulp

after_script:
  - php vendor/bin/coveralls -v
